{
  python-web-app-example = {
    description = "Python example web application";
    path = ./templates/python-web-app-example;
    welcomeText = ''
      This is a example web application demonstrating development of Python
      application using geospatial libraries.

      Geospatial Python dependencies are provided by Geonix. Non-geospatial
      Python dependencies are managed by Poetry. All other dependencies are
      coming from Nixpkgs.

      This application can use data generated by local Python server or from
      PostgreSQL/PostGIS database backend. Database container image is provided
      by Geonix.

      ## Usage

      * Lock flake dependencies

        ```
        nix flake lock
        ```

      * Add all files to git !

        ```
        git add *
        ```

      ### Development

      * Enter development shell

        ```
        nix develop
        ```

      * Install Python virtual environment managed by Poetry

        ```
        poetry install
        ```

      * Launch Python application development server (with local data backend)

        ```
        poetry run flask run --reload
        ```

      * Launch Python application development server (with database data backend)

        ```
        nix build .#postgresImage
        docker load < ./result
        docker-compose up -d

        BACKEND=db poetry run flask run --reload
        ```

      * Exit development shell

        ```
        exit
        ```

      ### Building application container image

      * Build container image

        ```
        nix build .#poetryAppImage
        ```

      * Load image to Docker

        ```
        docker load < result
        ```

      * Run container

        ```
        docker run -p 5000:5000 geonix-python-web-app-example
        ```

      ### Publish application and run it from GitHub

      * Create new GitHub repository

      * Add and commit all files to git

        ```
        git add *
        git commit -m "Python application from Geonix python-web-app-example template"
        ```

      * Push application to GitHub

        ```
        git remote add origin https://github.com/<OWNER>/<REPOSITORY>.git
        git branch -M master
        git push -u origin master
        ```

      * Launch application from GitHub

        ```
        nix run github:<OWNER>/<REPOSITORY>
        ```
        ```
        or try:
        nix run github:imincik/geonix-python-web-app-example
        ```

      ## More info

      * [Nixpkgs dockerTools](https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-dockerTools)
      * [mkPoetryApplication](https://github.com/nix-community/poetry2nix#mkPoetryApplication)
      * [Nix tutorials](https://nix.dev)
    '';
  };
}
