name: Publish a flake to flakestry.dev

on:
  push:
    tags:
      - "^nixos-[0-9]+.[0-9]+-[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: The existing tag to publish
        type: string
        required: true

jobs:
  publish-flake:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: flakestry/flakestry-publish@main
        with:
          version: "${{ inputs.tag || github.ref_name }}"
