name: Test geonix CLI

on:
  workflow_call:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v24

    - name: Set new project directory
      run: |
        echo "TEMPLATE_PROJECT_DIR=$(dirname $GITHUB_WORKSPACE)/template-project" >> $GITHUB_ENV

    - name: Prepare new project directory
      run: |
        mkdir $TEMPLATE_PROJECT_DIR

    - name: Test geonix init
      run: |
        git init

        nix run ${GITHUB_WORKSPACE}#geonixcli -- init

        git add *
      working-directory: ${{ env.TEMPLATE_PROJECT_DIR }}

    - name: Test geonix shell
      run: |
        nix run ${GITHUB_WORKSPACE}#geonixcli -- shell --command echo | grep GDAL
      working-directory: ${{ env.TEMPLATE_PROJECT_DIR }}

    - name: Test geonix search
      run: |
        nix run ${GITHUB_WORKSPACE}#geonixcli -- search gdal | grep 'geopkgs.gdal'
      working-directory: ${{ env.TEMPLATE_PROJECT_DIR }}

      # TODO: test `geonix up`
