name: Test container functions

on:
  workflow_call:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  test-function:
    strategy:
      fail-fast: false
      matrix:
        container:
          - postgresql
          - python
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v20

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config
      working-directory: tests/containers


    # python container
    - name: Test container (if python container)
      run: |
        nix build --accept-flake-config .#python
        docker load < ./result

        docker run -u "$(id -u):$(id -g)" test-python -c "import fiona; print(fiona.supported_drivers)"
      if: ${{ matrix.container == 'python' }}
      working-directory: tests/containers


    # postgresql container
    - name: Test container (if postgresql container)
      run: |
        nix build --accept-flake-config .#postgresql
        docker load < ./result

        docker run -d -u "$(id -u):$(id -g)" -v "$(pwd):/data" -p 15432:5432 test-postgresql

        nix develop .#ci \
        --command psql -U postgres -h localhost -p 15432 -d test -c 'SELECT postgis_full_version();'
      if: ${{ matrix.container == 'postgresql' }}
      working-directory: tests/containers
