name: Test custom images build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v19

    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: geonix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config
      working-directory: tests/custom-images


    - name: Prepare development shell environment
      run: >
        nix develop --accept-flake-config --command echo OK
      working-directory: tests/custom-images

    - name: Generate override template file
      run: >
        nix develop --command geonix override
      working-directory: tests/custom-images

    - name: Enable overrides template file in getPackages function
      run: |
        sed -i.orig "s|#.overridesFile.*=.*./overrides.nix;|overridesFile = ./overrides.nix;|" flake.nix
        git add overrides.nix
      working-directory: tests/custom-images


    # Custom GDAL
    - name: Add custom GDAL patch to override template file
      run: |
        patch -u overrides.nix -i ${GITHUB_WORKSPACE}/tests/custom-packages/gdal.patch
      working-directory: tests/custom-images

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config
      working-directory: tests/custom-images

    - name: Test if PostgreSQL container image depends on patched GDAL package
      run: >
       nix path-info --derivation --recursive .\#postgresqlImage | grep gdal-1000.0.0
      if: ${{ runner.os == 'Linux' }}
      working-directory: tests/custom-images


      # Custom PostgreSQL image
    - name: Add custom PostgreSQL patch to override template file
      run: |
        patch -u overrides.nix -i ${GITHUB_WORKSPACE}/tests/custom-images/postgresql-image.patch
      working-directory: tests/custom-images

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config
      working-directory: tests/custom-images

    - name: Test if PostgreSQL container image depends on pgrouting package
      run: >
       nix path-info --derivation --recursive .\#postgresqlImage | grep pgrouting
      if: ${{ runner.os == 'Linux' }}
      working-directory: tests/custom-images
